// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYX6oB0_7mWhMHbQ1bZVCLo71QGqBYJrs',
    appId: '1:386854922290:android:5e02d83c6458e03ac8b42b',
    messagingSenderId: '386854922290',
    projectId: 'palateful',
    storageBucket: 'palateful.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5mcTm6DovzxLr7KrgxFqLCcDXzsvEB7Y',
    appId: '1:386854922290:ios:899d64f146311162c8b42b',
    messagingSenderId: '386854922290',
    projectId: 'palateful',
    storageBucket: 'palateful.firebasestorage.app',
    iosBundleId: 'com.palateful.palateful',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_sv4AAno2BRIMgPreRUD7LbRl-5ayaA',
    appId: '1:386854922290:web:159241b671f65af1c8b42b',
    messagingSenderId: '386854922290',
    projectId: 'palateful',
    authDomain: 'palateful.firebaseapp.com',
    storageBucket: 'palateful.firebasestorage.app',
  );

}