[tool.poetry]
name = "worker"
version = "0.1.0"
description = "Palateful Celery worker for background tasks"
authors = ["Leonid Belyi"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.13"
celery = {extras = ["sqs"], version = "^5.5"}
pycurl = "^7.45"
psycopg2-binary = "^2.9.11"
yt-dlp = "^2025.3"
utils = {path = "../../libraries/utils", develop = true}
agent = {path = "../../libraries/agent", develop = true}

[tool.poetry.group.dev.dependencies]
ruff = "^0.11"
pytest = "^8.0"
pytest-cov = "^6.0"
pytest-html = "^4.0"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:', 'pragma: no cover']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../coverage/services/worker/html' --cov-report xml:'../../coverage/services/worker/coverage.xml' --html='../../reports/services/worker/unittests/html/index.html' --junitxml='../../reports/services/worker/unittests/junit.xml'"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
