#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting Palateful dev environment...${NC}"

# Start docker compose in background
echo -e "${YELLOW}Starting Docker services...${NC}"
docker compose up -d

# Wait for ngrok to be ready and get the tunnel URL
echo -e "${YELLOW}Waiting for ngrok tunnel...${NC}"
MAX_ATTEMPTS=30
ATTEMPT=0

while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
    NGROK_URL=$(curl --silent http://localhost:4040/api/tunnels 2>/dev/null | jq -r '.tunnels[0].public_url' 2>/dev/null)

    if [ -n "$NGROK_URL" ] && [ "$NGROK_URL" != "null" ]; then
        break
    fi

    ATTEMPT=$((ATTEMPT + 1))
    echo -e "  Attempt $ATTEMPT/$MAX_ATTEMPTS..."
    sleep 2
done

if [ -z "$NGROK_URL" ] || [ "$NGROK_URL" == "null" ]; then
    echo -e "${RED}Failed to get ngrok URL after $MAX_ATTEMPTS attempts${NC}"
    echo -e "${YELLOW}Check if NGROK_AUTHTOKEN is set in .env${NC}"
    exit 1
fi

echo -e "${GREEN}Ngrok URL: $NGROK_URL${NC}"

# Write the URL to a file for Flutter to use
echo "API_BASE_URL=$NGROK_URL" > app/.env.local

# Generate the Dart environment file with the ngrok URL
cat > app/lib/core/config/environment.generated.dart << EOF
// GENERATED FILE - DO NOT EDIT
// Generated by scripts/dev.sh
// Run 'yarn dev' or './scripts/dev.sh' to regenerate

class GeneratedEnvironment {
  static const String apiBaseUrl = '$NGROK_URL';
  static const DateTime generatedAt = DateTime($(date +%Y), $(date +%-m), $(date +%-d), $(date +%-H), $(date +%-M));
}
EOF

echo -e "${GREEN}Generated app/lib/core/config/environment.generated.dart${NC}"
echo ""
echo -e "${GREEN}====================================${NC}"
echo -e "${GREEN}Dev environment is ready!${NC}"
echo -e "${GREEN}====================================${NC}"
echo ""
echo -e "API URL: ${YELLOW}$NGROK_URL${NC}"
echo -e "Ngrok Dashboard: ${YELLOW}http://localhost:4040${NC}"
echo -e "API Health: ${YELLOW}$NGROK_URL/v1/health${NC}"
echo ""
echo -e "To run Flutter app:"
echo -e "  ${YELLOW}cd app && flutter run --dart-define=API_BASE_URL=$NGROK_URL${NC}"
echo ""
echo -e "Or use the generated environment file in your app."
echo ""
echo -e "To view logs: ${YELLOW}docker compose logs -f${NC}"
echo -e "To stop: ${YELLOW}docker compose down${NC}"
