"""Suggestion model for AI-generated meal suggestions."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, UUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from utils.models.base import Base

if TYPE_CHECKING:
    from utils.models.recipe import Recipe
    from utils.models.user import User


class Suggestion(Base):
    """
    AI-generated suggestion model.

    Suggestions are proactive recommendations generated by the agent,
    triggered by events like daily schedules, pantry updates, or expiring ingredients.
    """

    __tablename__ = "suggestions"

    # Content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    suggestion_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # "recipe" | "meal_plan" | "tip" | "use_it_up"

    # Foreign keys
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    recipe_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID, ForeignKey("recipes.id", ondelete="SET NULL"), nullable=True
    )

    # Trigger info
    trigger_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # "daily" | "pantry_update" | "expiring"
    trigger_context: Mapped[dict] = mapped_column(JSONB, default={}, nullable=False)

    # State
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_dismissed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Auto-dismiss after this time
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    user: Mapped["User"] = relationship(back_populates="suggestions")
    recipe: Mapped["Recipe | None"] = relationship(back_populates="suggestions")
    notifications: Mapped[list["Notification"]] = relationship(
        back_populates="suggestion", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return self.get_repr(["id", "suggestion_type", "trigger_type", "is_read"])


# Import here to avoid circular imports
from utils.models.notification import Notification  # noqa: E402, F401
