#!/usr/bin/env python3
"""Perf-audit diff helper — read PERF_AUDIT_CSV lines on stdin, then
either write a budget YAML (`--mode capture`) or compare against one
(`--mode assert`).

Used by `bin/perf-audit`. Keeps the bash driver thin and dependency-
free; YAML parsing lives here where PyYAML is already available.

Exit codes:
  0 — capture success, or assert clean.
  1 — assert detected budget violations (one or more screens exceed).
  2 — I/O / malformed input.
"""
from __future__ import annotations

import argparse
import collections
import re
import sys
from typing import Dict

try:
    import yaml  # type: ignore
except ImportError:
    sys.stderr.write(
        "perf-audit-diff: PyYAML missing. Install with `pip install pyyaml`.\n",
    )
    sys.exit(2)


CSV_LINE = re.compile(r"^PERF_AUDIT_CSV,([^,]+),([^,]+),(\d+)\s*$")


def parse_csv(stream) -> Dict[str, Dict[str, int]]:
    """CSV sentinels → {screen: {endpoint: count}}."""
    screens: Dict[str, Dict[str, int]] = collections.defaultdict(
        lambda: collections.defaultdict(int)
    )
    for raw in stream:
        match = CSV_LINE.match(raw.rstrip("\n"))
        if not match:
            continue
        screen, endpoint, count = match.groups()
        screens[screen][endpoint] += int(count)
    return {k: dict(v) for k, v in screens.items()}


def to_budget_dict(screens: Dict[str, Dict[str, int]]) -> Dict[str, object]:
    out: Dict[str, Dict[str, object]] = {}
    for screen in sorted(screens):
        endpoints = screens[screen]
        out[screen] = {
            "total": sum(endpoints.values()),
            "endpoints": dict(sorted(endpoints.items())),
        }
    return {"screens": out}


HEADER = """\
# Perf audit per-screen endpoint budgets — generated by
# `bin/perf-audit --capture`, hand-edited for intentional raises.
#
# Raising a budget requires:
#   1. Rationale in the PR description.
#   2. A matching line in tools/perf-budget-waivers.txt (format
#      screen:endpoint:rationale).
#   3. An `actions/labeler` auto-applied `perf-budget-change` label
#      (see ptd-5 CI step).
#
# `total` is the sum of `endpoints` for the screen; both are asserted
# against in `--assert` mode.
"""


def capture(path: str, screens: Dict[str, Dict[str, int]]) -> int:
    budget = to_budget_dict(screens)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        yaml.safe_dump(budget, fh, sort_keys=False, default_flow_style=False)
    endpoint_count = sum(len(v) for v in screens.values())
    sys.stderr.write(
        f"perf-audit-diff: wrote {path} "
        f"({len(screens)} screens, {endpoint_count} endpoints)\n",
    )
    return 0


def assert_budget(path: str, screens: Dict[str, Dict[str, int]]) -> int:
    try:
        with open(path, encoding="utf-8") as fh:
            budget = yaml.safe_load(fh) or {}
    except FileNotFoundError:
        sys.stderr.write(
            f"perf-audit-diff: budget {path} not found; run `--capture` first.\n",
        )
        return 2

    budget_screens = budget.get("screens", {}) or {}
    violations = []  # (screen, key, budget, observed)
    for screen in sorted(screens):
        endpoints = screens[screen]
        bs = budget_screens.get(screen, {}) or {}
        budget_total = int(bs.get("total", 0))
        observed_total = sum(endpoints.values())
        if observed_total > budget_total:
            violations.append((screen, "<total>", budget_total, observed_total))
        be = bs.get("endpoints", {}) or {}
        for endpoint in sorted(endpoints):
            observed = endpoints[endpoint]
            budgeted = int(be.get(endpoint, 0))
            if observed > budgeted:
                violations.append((screen, endpoint, budgeted, observed))

    # Render a diff table regardless of outcome — CI job summary
    # always shows the per-screen picture so reviewers have context.
    render_diff(screens, budget_screens)

    if not violations:
        sys.stderr.write("perf-audit-diff: OK (all screens within budget)\n")
        return 0

    sys.stderr.write(f"\nperf-audit-diff: {len(violations)} budget violation(s):\n")
    for screen, key, budgeted, observed in violations:
        delta = observed - budgeted
        sys.stderr.write(
            f"  {screen}: {key} — budget {budgeted}, observed {observed} (+{delta})\n",
        )
    return 1


def render_diff(
    observed: Dict[str, Dict[str, int]],
    budget_screens: Dict[str, dict],
) -> None:
    """Print a pipe-separated per-screen table. Columns: screen |
    observed-total | budget-total | delta | status."""
    header = f"| {'screen':<24} | {'observed':>8} | {'budget':>6} | {'delta':>5} | status |"
    divider = "|" + "-" * (len(header) - 2) + "|"
    sys.stdout.write(header + "\n")
    sys.stdout.write(divider + "\n")
    all_screens = sorted(set(observed) | set(budget_screens))
    for screen in all_screens:
        observed_total = sum(observed.get(screen, {}).values())
        bs = budget_screens.get(screen, {}) or {}
        budget_total = int(bs.get("total", 0))
        delta = observed_total - budget_total
        if delta > 0:
            status = "FAIL"
        elif delta < 0:
            status = "UNDER"
        else:
            status = "OK"
        sys.stdout.write(
            f"| {screen:<24} | {observed_total:>8} | {budget_total:>6} | "
            f"{delta:>+5} | {status:<6} |\n"
        )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Diff observed perf-audit CSV sentinels against a budget YAML.",
    )
    parser.add_argument("--mode", choices=["capture", "assert"], required=True)
    parser.add_argument("--budget", required=True, help="Path to perf-budgets.yaml")
    args = parser.parse_args()

    screens = parse_csv(sys.stdin)
    if not screens:
        sys.stderr.write("perf-audit-diff: no CSV sentinels found on stdin.\n")
        return 2

    if args.mode == "capture":
        return capture(args.budget, screens)
    return assert_budget(args.budget, screens)


if __name__ == "__main__":
    sys.exit(main())
